FROM php:7.4-cli
RUN apt-get update -y \
  && apt-get install -y \
     libxml2-dev \
     git \
     jq \
  && apt-get clean -y \
  && docker-php-ext-install soap


ENV TYPO3_EXTENSION_DIR  "/extension"
ENV WH_WORK_DIR  "/var/webhook/data"

COPY ./upload/ /upload/
COPY ./upload-entrypoint /usr/local/bin/upload
COPY ./autoupload-entrypoint /usr/local/bin/autoupload

VOLUME [ "/var/webhook/data" ]
WORKDIR "/upload"
